### PR TITLE
[Board] Require io/console for winsize

### LINKED ISSUE #9: exception when trying to wrap to the window size
System `ruby` on 10.11.6

```
$ ruby --version
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
```

System `gem` on 10.11.6

```
$ gem --version
2.0.14.1

```

Stacktrace:

```
/Users/Samantha/.gem/ruby/2.0.0/gems/cork-0.1.0/lib/cork/board.rb:333:in `wrap_string': undefined method `winsize' for #<IO:<STDOUT>> (NoMethodError)
    from /Users/Samantha/.gem/ruby/2.0.0/gems/cork-0.1.0/lib/cork/board.rb:80:in `puts_indented'
    from /Users/Samantha/.gem/ruby/2.0.0/gems/claide-plugins-0.9.1/lib/claide/command/plugins_helper.rb:79:in `block in print_plugin'
    from /Users/Samantha/.gem/ruby/2.0.0/gems/cork-0.1.0/lib/cork/board.rb:234:in `title'
    from /Users/Samantha/.gem/ruby/2.0.0/gems/claide-plugins-0.9.1/lib/claide/command/plugins_helper.rb:78:in `print_plugin'
    from /Users/Samantha/.gem/ruby/2.0.0/gems/claide-plugins-0.9.1/lib/claide/command/plugins/list.rb:27:in `block (2 levels) in run'
    from /Users/Samantha/.gem/ruby/2.0.0/gems/claide-plugins-0.9.1/lib/claide/command/plugins/list.rb:26:in `each'
    from /Users/Samantha/.gem/ruby/2.0.0/gems/claide-plugins-0.9.1/lib/claide/command/plugins/list.rb:26:in `block in run'
    from /Users/Samantha/.gem/ruby/2.0.0/gems/cork-0.1.0/lib/cork/board.rb:234:in `title'
    from /Users/Samantha/.gem/ruby/2.0.0/gems/claide-plugins-0.9.1/lib/claide/command/plugins/list.rb:25:in `run'
    from /Users/Samantha/.gem/ruby/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
    from /Users/Samantha/.gem/ruby/2.0.0/gems/danger-0.10.1/bin/danger:5:in `<top (required)>'
    from /Users/Samantha/.gem/ruby/2.0.0/bin/danger:23:in `load'
    from /Users/Samantha/.gem/ruby/2.0.0/bin/danger:23:in `<main>'
```

### PR DESCRIPTION
**Pull request by segiddins**
Should close #9

### CODE REVIEW

**Comment by orta** [comment]
I just [got this](https://travis-ci.org/danger/danger/jobs/147047918) - think it's the same thing? 

```
$ bundle exec danger --verbose
Errno::ENOTTY: Inappropriate ioctl for device
  /home/travis/build/danger/danger/bundle/ruby/2.1.0/gems/cork-0.1.0/lib/cork/board.rb:333:in `winsize'
  /home/travis/build/danger/danger/bundle/ruby/2.1.0/gems/cork-0.1.0/lib/cork/board.rb:333:in `wrap_string'
  /home/travis/build/danger/danger/bundle/ruby/2.1.0/gems/cork-0.1.0/lib/cork/board.rb:141:in `labeled'
  /home/travis/build/danger/danger/lib/danger/plugin_support/plugin_linter.rb:77:in `block (3 levels) in print_summary'
  /home/travis/build/danger/danger/lib/danger/plugin_support/plugin_linter.rb:73:in `each'
  /home/travis/build/danger/danger/lib/danger/plugin_support/plugin_linter.rb:73:in `block (2 levels) in print_summary'
  /home/travis/build/danger/danger/bundle/ruby/2.1.0/gems/cork-0.1.0/lib/cork/board.rb:184:in `section'
  /home/travis/build/danger/danger/lib/danger/plugin_support/plugin_linter.rb:72:in `block in print_summary'
  /home/travis/build/danger/danger/lib/danger/plugin_support/plugin_linter.rb:86:in `call'
  /home/travis/build/danger/danger/lib/danger/plugin_support/plugin_linter.rb:86:in `print_summary'
  /home/travis/build/danger/danger/lib/danger/commands/plugins/plugin_lint.rb:48:in `run'
  /home/travis/build/danger/danger/bundle/ruby/2.1.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
  /home/travis/build/danger/danger/bin/danger:5:in `<top (required)>'
  /home/travis/build/danger/danger/bundle/ruby/2.1.0/bin/danger:23:in `load'
  /home/travis/build/danger/danger/bundle/ruby/2.1.0/bin/danger:23:in `<top (required)>'
```

I'm doing this: 

```
core_plugins_docs = `bundle exec danger plugins lint #{core_plugins.join " "} --warnings-as-errors`
```

Which would use the board

**Comment by orta** [comment]
Doesn't feel like it, [this build](https://travis-ci.org/danger/danger/jobs/147048836#L197) - with this branch failed. 

Do you have opinions on me adding something similar to the fallback found in pry?  https://github.com/pry/pry/commit/fc522f837a59fe2003c667a48860529610d6f7d8#diff-3b4e68fce7d91685b14c014dea99168fR25

**Comment by segiddins** [comment]
@orta should be fixed now

**Comment by orta** [comment]
Oh, that makes sense 👍

**Comment by orta** [comment]
Yep 👍

**Pull request merged**
